// Copy de marketing: todo lo que NO existe en strings.xml de la app.
// Los headlines llevan HTML crudo (<br> y <span class="hl">) porque el corte de
// linea y la parte resaltada son decisiones tipograficas por idioma.

export const COPY = {
  'en-US': {
    home_eyebrow:       'Market Trends',
    home_headline:      'Spot the market\'s<br><span class="hl">biggest movers</span>',
    detail_eyebrow:     'Compare &amp; Save',
    detail_headline:    'The <span class="hl">lowest price</span><br>across marketplaces',
    alerts_eyebrow:     'Price Alerts',
    alerts_headline:    'Get notified the<br>moment <span class="hl">prices drop</span>',
    history_eyebrow:    'Price History',
    history_headline:   'Buy the dip,<br><span class="hl">sell the spike</span>',
    portfolio_eyebrow:  'Portfolio',
    portfolio_headline: 'Know what your<br>inventory is <span class="hl">really worth</span>',
    search_eyebrow:     'Skin Search',
    search_headline:    'Search <span class="hl">20,000+ skins</span><br>with smart filters',
    fg_headline:        'Track market prices<br>for <span class="hl">CS2 skins</span>',
    fg_chip_alerts:     'Price alerts',
    fg_chip_movers:     'Top movers',
    fg_chip_portfolio:  'Portfolio',
    sorted_by_value:    'Sorted by value',
    low_30d:            '30d low',
    high_30d:           '30d high',
    alert_below:        'Below',
    alert_above:        'Above',
    today_change:       '+3.2% today',
    notif_title:        '🔻 Price alert: AK-47 | Redline (FT)',
    notif_body:         'Dropped to $42.10 — below your $45.00 target',
    notif_meta:         'CS2 SkinFlip · now',
  },
  'es-ES': {
    home_eyebrow:       'Tendencias del mercado',
    home_headline:      'Detecta los<br><span class="hl">mayores movimientos</span>',
    detail_eyebrow:     'Compara y ahorra',
    detail_headline:    'El <span class="hl">precio más bajo</span><br>de todos los mercados',
    alerts_eyebrow:     'Alertas de precio',
    alerts_headline:    'Entérate en cuanto<br><span class="hl">baje el precio</span>',
    history_eyebrow:    'Historial de precios',
    history_headline:   'Compra en la caída,<br><span class="hl">vende en el pico</span>',
    portfolio_eyebrow:  'Portafolio',
    portfolio_headline: 'Descubre lo que<br><span class="hl">vale de verdad</span><br>tu inventario',
    search_eyebrow:     'Búsqueda de skins',
    search_headline:    'Busca entre <span class="hl">20.000+ skins</span><br>con filtros inteligentes',
    fg_headline:        'Sigue los precios<br>de las <span class="hl">skins de CS2</span>',
    fg_chip_alerts:     'Alertas de precio',
    fg_chip_movers:     'Más movidos',
    fg_chip_portfolio:  'Portafolio',
    sorted_by_value:    'Por valor',
    low_30d:            'Mín. 30d',
    high_30d:           'Máx. 30d',
    alert_below:        'Por debajo de',
    alert_above:        'Por encima de',
    today_change:       '+3,2% hoy',
    notif_title:        '🔻 Alerta de precio: AK-47 | Redline (FT)',
    notif_body:         'Bajó a $42.10 — por debajo de tu objetivo de $45.00',
    notif_meta:         'CS2 SkinFlip · ahora',
  },
  'pt-BR': {
    home_eyebrow:       'Tendências do mercado',
    home_headline:      'Descubra as<br><span class="hl">maiores variações</span>',
    detail_eyebrow:     'Compare e economize',
    detail_headline:    'O <span class="hl">menor preço</span><br>entre os mercados',
    alerts_eyebrow:     'Alertas de preço',
    alerts_headline:    'Saiba na hora em que<br>o <span class="hl">preço cair</span>',
    history_eyebrow:    'Histórico de preços',
    history_headline:   'Compre na queda,<br><span class="hl">venda no pico</span>',
    portfolio_eyebrow:  'Portfólio',
    portfolio_headline: 'Saiba quanto seu<br>inventário <span class="hl">vale de verdade</span>',
    search_eyebrow:     'Busca de skins',
    search_headline:    'Busque <span class="hl">20.000+ skins</span><br>com filtros inteligentes',
    fg_headline:        'Acompanhe os preços<br>das <span class="hl">skins de CS2</span>',
    fg_chip_alerts:     'Alertas de preço',
    fg_chip_movers:     'Maiores variações',
    fg_chip_portfolio:  'Portfólio',
    sorted_by_value:    'Por valor',
    low_30d:            'Mín. 30d',
    high_30d:           'Máx. 30d',
    alert_below:        'Abaixo de',
    alert_above:        'Acima de',
    today_change:       '+3,2% hoje',
    notif_title:        '🔻 Alerta de preço: AK-47 | Redline (FT)',
    notif_body:         'Caiu para $42.10 — abaixo da sua meta de $45.00',
    notif_meta:         'CS2 SkinFlip · agora',
  },
  'ru-RU': {
    home_eyebrow:       'Тренды рынка',
    home_headline:      'Следи за<br><span class="hl">лидерами движения</span>',
    detail_eyebrow:     'Сравни и сэкономь',
    detail_headline:    '<span class="hl">Лучшая цена</span><br>на всех площадках',
    alerts_eyebrow:     'Ценовые алерты',
    alerts_headline:    'Узнай сразу,<br>как <span class="hl">цена упадёт</span>',
    history_eyebrow:    'История цен',
    history_headline:   'Покупай на спаде,<br><span class="hl">продавай на пике</span>',
    portfolio_eyebrow:  'Портфель',
    portfolio_headline: 'Узнай, сколько<br><span class="hl">реально стоит</span><br>твой инвентарь',
    search_eyebrow:     'Поиск скинов',
    search_headline:    'Ищи среди <span class="hl">20 000+ скинов</span><br>с умными фильтрами',
    fg_headline:        'Отслеживай цены<br>на <span class="hl">скины CS2</span>',
    fg_chip_alerts:     'Ценовые алерты',
    fg_chip_movers:     'Лидеры движения',
    fg_chip_portfolio:  'Портфель',
    sorted_by_value:    'По стоимости',
    low_30d:            'Мин. 30д',
    high_30d:           'Макс. 30д',
    alert_below:        'Ниже',
    alert_above:        'Выше',
    today_change:       '+3,2% сегодня',
    notif_title:        '🔻 Ценовой алерт: AK-47 | Redline (FT)',
    notif_body:         'Упал до $42.10 — ниже твоей цели $45.00',
    notif_meta:         'CS2 SkinFlip · сейчас',
  },
  'tr-TR': {
    home_eyebrow:       'Piyasa trendleri',
    home_headline:      'En çok<br><span class="hl">hareketlenenleri</span> gör',
    detail_eyebrow:     'Karşılaştır ve kazan',
    detail_headline:    'Tüm pazarlardaki<br><span class="hl">en düşük fiyat</span>',
    alerts_eyebrow:     'Fiyat alarmları',
    alerts_headline:    '<span class="hl">Fiyat düştüğü an</span><br>haberin olsun',
    history_eyebrow:    'Fiyat geçmişi',
    history_headline:   'Düşüşte al,<br><span class="hl">zirvede sat</span>',
    portfolio_eyebrow:  'Portföy',
    portfolio_headline: 'Envanterinin<br><span class="hl">gerçek değerini</span> öğren',
    search_eyebrow:     'Skin arama',
    search_headline:    '<span class="hl">20.000+ skin</span> arasında<br>akıllı filtrelerle ara',
    fg_headline:        '<span class="hl">CS2 skin</span> fiyatlarını<br>takip et',
    fg_chip_alerts:     'Fiyat alarmları',
    fg_chip_movers:     'Hareketlenenler',
    fg_chip_portfolio:  'Portföy',
    sorted_by_value:    'Değere göre',
    low_30d:            '30g en düşük',
    high_30d:           '30g en yüksek',
    alert_below:        'Altında',
    alert_above:        'Üstünde',
    today_change:       'bugün +%3,2',
    notif_title:        '🔻 Fiyat alarmı: AK-47 | Redline (FT)',
    notif_body:         '$42.10 seviyesine düştü — $45.00 hedefinin altında',
    notif_meta:         'CS2 SkinFlip · şimdi',
  },
  'pl-PL': {
    home_eyebrow:       'Trendy rynkowe',
    home_headline:      'Zobacz<br><span class="hl">największe zmiany</span>',
    detail_eyebrow:     'Porównaj i oszczędzaj',
    detail_headline:    '<span class="hl">Najniższa cena</span><br>na wszystkich rynkach',
    alerts_eyebrow:     'Alerty cenowe',
    alerts_headline:    'Dowiedz się, gdy<br><span class="hl">cena spadnie</span>',
    history_eyebrow:    'Historia cen',
    history_headline:   'Kupuj na dołku,<br><span class="hl">sprzedawaj na górce</span>',
    portfolio_eyebrow:  'Portfel',
    portfolio_headline: 'Sprawdź, ile<br><span class="hl">naprawdę wart</span> jest<br>twój ekwipunek',
    search_eyebrow:     'Wyszukiwanie skinów',
    search_headline:    'Przeszukaj <span class="hl">20 000+ skinów</span><br>z inteligentnymi filtrami',
    fg_headline:        'Śledź ceny<br><span class="hl">skinów CS2</span>',
    fg_chip_alerts:     'Alerty cenowe',
    fg_chip_movers:     'Największe zmiany',
    fg_chip_portfolio:  'Portfel',
    sorted_by_value:    'Wg wartości',
    low_30d:            'Min. 30d',
    high_30d:           'Maks. 30d',
    alert_below:        'Poniżej',
    alert_above:        'Powyżej',
    today_change:       '+3,2% dziś',
    notif_title:        '🔻 Alert cenowy: AK-47 | Redline (FT)',
    notif_body:         'Spadł do $42.10 — poniżej twojego celu $45.00',
    notif_meta:         'CS2 SkinFlip · teraz',
  },
}

export function c(playLocale, key) {
  const v = COPY[playLocale]?.[key]
  if (v === undefined) throw new Error(`Missing copy: ${key} (${playLocale})`)
  return v
}
